language: node_js
cache:
  directories: "node_modules"

before_script:
  - npm i

script:
  - npm run lint
  - npm run build

before_deploy:
  - npm install netlify-cli -g

deploy:
  provider: script
  script: netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
  skip_cleanup: true
  on:
    branch: master
